from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd
from datetime import datetime

'143568'

reg = []
val = []
for region in regions:
    if '<' not in region.text:
        reg.append(str(region.text))
        val.append(str(region.attrs['value']))

In [125]:
sale = []
for vals,regs in zip(val,reg):
    p = 'http://www.digitalsalesdata.com/diydsd.php?Region='
    page = urlopen(p+vals)
    page = BeautifulSoup(page,'lxml')
    data = page.find('table').findAll('td')[4:48]
    for i,n in enumerate(data):
        if i%36 == 0:
            sale.append([regs,datetime.now().strftime('%m/%d/%Y %H:%M'),n.text,data[i+3].text])
sale=pd.DataFrame(sale, columns = ['country','time','rank','sale']) 
        #for item in ['1','2','3','4','5','10','15','20']:
            #if n.text == item:
               # print(regs)
                #print(data[i+3].text)
                #sale.append([regs,datetime.now().strftime('%m/%d/%Y %H:%M'),item,data[i+3].text])
#sales = pd.DataFrame(sale, columns = ['country','time','rank','sale']) 
sales = sales.append(sale)
sale.to_csv('global_sales_data_0214.csv')

In [115]:
sales.to_csv('global_sales_data.csv')

In [145]:
sales.shape

(714, 5)

In [116]:
sales = pd.read_csv('global_sales_data.csv')

In [146]:
sales[(sales['rank'] == 1)&(sales['sale'] ==1)]

     Unnamed: 0                 country rank sale              time
4           4.0                Anguilla    1    1  02/14/2017 01:58
6           6.0       Antigua & Barbuda    1    1  02/14/2017 01:58
10         10.0                 Armenia    1    1  02/14/2017 01:58
20         20.0                 Bahrain    1    1  02/14/2017 01:58
22         22.0                Barbados    1    1  02/14/2017 01:58
24         24.0                 Belarus    1    1  02/14/2017 01:58
28         28.0                  Belize    1    1  02/14/2017 01:58
30         30.0                 Bermuda    1    1  02/14/2017 01:58
32         32.0                 Bolivia    1    1  02/14/2017 01:59
34         34.0                Botswana    1    1  02/14/2017 01:59
38         38.0  British Virgin Islands    1    1  02/14/2017 01:59
44         44.0            Burkina-Faso    1    1  02/14/2017 01:59
46         46.0                Cambodia    1    1  02/14/2017 01:59
50         50.0              Cape Verde    1    1  02/14/2017 01:59
52         52.0          Cayman Islands    1    1  02/14/2017 01:59
58         58.0              Costa Rica    1    1  02/14/2017 01:59
60         60.0                  Cyprus    1    1  02/14/2017 01:59
66         66.0                Dominica    1    1  02/14/2017 01:59
72         72.0                   Egypt    1    1  02/14/2017 01:59
74         74.0             El Salvador    1    1  02/14/2017 02:00
76         76.0                 Estonia    1    1  02/14/2017 02:00
78         78.0                    Fiji    1    1  02/14/2017 02:00
84         84.0                  Gambia    1    1  02/14/2017 02:00
88         88.0                   Ghana    1    1  02/14/2017 02:00
92         92.0                 Grenada    1    1  02/14/2017 02:00
94         94.0               Guatemala    1    1  02/14/2017 02:00
96         96.0           Guinea-Bissau    1    1  02/14/2017 02:00
98         98.0                Honduras    1    1  02/14/2017 02:00
116       116.0                  Jordan    1    1  02/14/2017 02:00
120       120.0                   Kenya    1    1  02/14/2017 02:00
..          ...                     ...  ...  ...               ...
124       124.0                    Laos    1    1  02/14/2017 02:01
126       126.0                  Latvia    1    1  02/14/2017 02:01
128       128.0                 Lebanon    1    1  02/14/2017 02:01
130       130.0               Lithuania    1    1  02/14/2017 02:01
134       134.0                   Macau    1    1  02/14/2017 02:01
138       138.0                   Malta    1    1  02/14/2017 02:01
140       140.0               Mauritius    1    1  02/14/2017 02:01
144       144.0              Micronesia    1    1  02/14/2017 02:01
146       146.0                 Moldova    1    1  02/14/2017 02:01
148       148.0                Mongolia    1    1  02/14/2017 02:01
150       150.0              Mozambique    1    1  02/14/2017 02:01
154       154.0                   Nepal    1    1  02/14/2017 02:01
160       160.0               Nicaragua    1    1  02/14/2017 02:01
162       162.0                   Niger    1    1  02/14/2017 02:01
168       168.0                    Oman    1    1  02/14/2017 02:02
172       172.0        Papua New Guinea    1    1  02/14/2017 02:02
174       174.0                Paraguay    1    1  02/14/2017 02:02
184       184.0                   Qatar    1    1  02/14/2017 02:02
190       190.0   Saint Kitts and Nevis    1    1  02/14/2017 02:02
192       192.0            Saudi Arabia    1    1  02/14/2017 02:02
198       198.0                Slovenia    1    1  02/14/2017 02:02
204       204.0               Sri Lanka    1    1  02/14/2017 02:02
206       206.0               Swaziland    1    1  02/14/2017 02:02
214       214.0              Tajikistan    1    1  02/14/2017 02:03
218       218.0     Trinidad and Tobago    1    1  02/14/2017 02:03
222       222.0            Turkmenistan    1    1  02/14/2017 02:03
224       224.0                  Uganda    1    1  02/14/2017 02:03
230       230.0              Uzbekistan    1    1  02/14/2017 02:03
232       232.0               Venezuela    1    1  02/14/2017 02:03
236       236.0                Zimbabwe    1    1  02/14/2017 02:03

[61 rows x 5 columns]

In [137]:
sale['rank'] = pd.to_numeric(sale['rank'])
sale['sale'] = pd.to_numeric(sale['sale'])